@startuml
hide empty members

abstract class AbstractService [[java:fr.insee.arc.core.service.AbstractService]] {
}

interface IApiService [[java:fr.insee.arc.core.service.IApiService]] {
}

interface IDbConstant [[java:fr.insee.arc.core.model.IDbConstant]] {
}

interface IConstanteNumerique [[java:fr.insee.siera.textutils.IConstanteNumerique]] {
}

abstract class AbstractPhaseService [[java:fr.insee.arc.core.service.AbstractPhaseService]] {
}

interface IPhaseService [[java:fr.insee.arc.core.service.IPhaseService]] {
}

abstract class "AbstractThreadRunnerService<T extends AbstractThreadService>" as AbstractThreadRunnerService_AbstractThreadService_ [[java:fr.insee.arc.core.service.AbstractThreadRunnerService]] {
}

class ApiChargementService [[java:fr.insee.arc.core.service.ApiChargementService]] {
}

interface IApiServiceWithoutOutputTable [[java:fr.insee.arc.core.service.IApiServiceWithoutOutputTable]] {
}

class ApiControleService [[java:fr.insee.arc.core.service.ApiControleService]] {
}

interface IApiServiceWithOutputTable [[java:fr.insee.arc.core.service.IApiServiceWithOutput]] {
}

class ApiFiltrageService [[java:fr.insee.arc.core.service.ApiFiltrageService]] {
}

class ApiIdentificationService [[java:fr.insee.arc.core.service.ApiIdentificationService]] {
}

class ApiInitialisationService [[java:fr.insee.arc.core.service.ApiInitialisationService]] {
}

class ApiNormageService [[java:fr.insee.arc.core.service.ApiNormageService]] {
}

class ApiReceptionService [[java:fr.insee.arc.core.service.ApiReceptionService]] {
}

class MappingService [[java:fr.insee.arc.core.service.mapping.MappingService]] {
}


package Thread <<Rectangle>> {

abstract class AbstractThreadService [[java:fr.insee.arc.core.service.thread.AbstractThreadService]] {
}

interface Runnable [[java:java.lang.Runnable]] {
}

class ThreadChargementService [[java:fr.insee.arc.core.service.thread.ThreadChargementService]] {
}

class ThreadControleService [[java:fr.insee.arc.core.service.thread.ThreadControleervice]]{
}

class ThreadFiltrageService [[java:fr.insee.arc.core.service.thread.ThreadFiltrageService]]{
}

class ThreadIdentificationService [[java:fr.insee.arc.core.service.thread.ThreadIdentificationService]]{
}

class ThreadMappingService [[java:fr.insee.arc.core.service.thread.ThreadMappingService]]{
}

class ThreadNormageService [[java:fr.insee.arc.core.service.thread.ThreadNormageService]]{
}

interface IRulesUserService [[java:fr.insee.arc.core.service.thread.IRulesUserService]] {

}
}


AbstractService <|-- AbstractPhaseService
IApiService <|.. AbstractService
IDbConstant <|.. AbstractService
IConstanteNumerique <|.. AbstractService
IPhaseService <|.. AbstractPhaseService
AbstractService <|-- AbstractThreadService
Runnable <|.. AbstractThreadService
AbstractPhaseService <|-- AbstractThreadRunnerService_AbstractThreadService_
AbstractThreadRunnerService_AbstractThreadService_ <|-- ApiChargementService

IApiServiceWithOutputTable <|.up. ApiChargementService

AbstractThreadRunnerService_AbstractThreadService_ <|-- ApiControleService
IApiServiceWithOutputTable <|.up. ApiControleService
AbstractThreadRunnerService_AbstractThreadService_ <|-- ApiFiltrageService
IApiServiceWithOutputTable <|.up. ApiFiltrageService
AbstractThreadRunnerService_AbstractThreadService_ <|-- ApiIdentificationService
IApiServiceWithoutOutputTable <|.up. ApiIdentificationService
IApiServiceWithoutOutputTable <|.up. ApiInitialisationService
IApiServiceWithoutOutputTable <|.up. ApiReceptionService


AbstractPhaseService <|-- ApiInitialisationService
AbstractThreadRunnerService_AbstractThreadService_ <|-- ApiNormageService
IApiServiceWithOutputTable <|.up. ApiNormageService
AbstractPhaseService <|-- ApiReceptionService
AbstractThreadRunnerService_AbstractThreadService_ <|-- MappingService
IApiServiceWithOutputTable <|.up. MappingService

AbstractThreadService <|-right- ThreadChargementService
AbstractThreadService <|-- ThreadControleService
AbstractThreadService <|-- ThreadFiltrageService
AbstractThreadService <|-- ThreadIdentificationService
AbstractThreadService <|-- ThreadMappingService
AbstractThreadService <|-- ThreadNormageService

IRulesUserService <|.. ThreadNormageService
IRulesUserService <|.. ThreadFiltrageService

AbstractThreadRunnerService_AbstractThreadService_ -right->"1..*" AbstractThreadService : lance

@enduml