name: release-on-tag

on:
  push:
   tags:
     - version-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Package with Maven
      run: mvn package -Denv.arcVersion=${GITHUB_REF#refs/*/version-} -Denv.arcVersionDate=$(date +'%Y-%m-%d')
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*/target/*.war,arc-batch/target/ArcMain.jar"
        body: "New automated release"
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
